MONGO_URI = "mongodb+srv://puseletso55:Daniel%409615@townshipbusinesschatbot.awtrt6h.mongodb.net/?retryWrites=true&w=majority&appName=TownshipBusinessChatbot"

[cloudinary]
cloud_name = "vehicle-inspection"
api_key = "245215129716347"
api_secret = "TP31VYjYA2GeYx2V8baoFfZp3ao"
